apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: o5ysl2zqz-nodejs-gitops
  description: This is GitOps manifest for o5ysl2zqz-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=o5ysl2zqz-nodejs
    backstage.io/kubernetes-id: o5ysl2zqz-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: o5ysl2zqz-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:o5ysl2zqz-nodejs
